version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo-go
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - vol1:/data/db
    networks:
      - mongodb_network

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - MONGO_URI_DB=mongodb://root:root@mongo:27017/?connect=direct
      - PLANETS_API_BASE_URL=https://swapi.dev/api/planets?search=
      - PORT=8080
    networks:
      - mongodb_network
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge

volumes:
  vol1:
    driver: local